<?php

namespace solods\fblike;


use yii\web\View;

class Widget extends \yii\base\Widget
{
    public $headlineText = 'Подписывайтесь на нас в Фейсбук!';
    public $secondaryText = 'Спасибо!';
    public $delay = 5;
    public $cookieExpiry = 7;
    public $colour = '#c3262f';
    public $fb;
    public $logo;
    public $asset;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $view = $this->getView();
        $this->asset = Asset::register($view);
        $template = $this->render('index', [
            'headlineText' => $this->headlineText,
            'secondaryText' => $this->secondaryText,
            'colour' => $this->colour,
            'fb' => $this->fb,
            'logo' => $this->logo]);
        $template = addslashes(str_replace(["\r", "\n"], "", $template));
        $js = <<<JS
        (function(_scope) {	
        fbLike.init({
                width: 380,
                height: 107,
                cookieExp: {$this->cookieExpiry},
                delay: {$this->delay}, 
                showOnDelay: true,
                html: "{$template}"
                });
		})({});
JS;
        $view->registerJs($js, View::POS_END);
    }

    public function run()
    {
        return '';
    }
}